### PR TITLE
Settings service

### PR DESCRIPTION
**Pull request by lotzk**

### CODE REVIEW

**Comment by Alexander-Krause** [comment]
@dan0x09 and @Malte-Hansen : I will notify you guys when this is tested and merged.

**Comment by Alexander-Krause** [comment]
@lotzk I tagged the latest master-Branch snapshot of the [explorviz-backend-shared project](https://github.com/ExplorViz/explorviz-backend-shared/releases/tag/v1.3.16). If I change the `sharedProjectVersion=v1.3.15` to `1.3.16` in the [gradle.properties](https://github.com/ExplorViz/explorviz-backend/blob/settings-service/gradle.properties) file, the settings stuff cannot be resolved in the user-service, e.g., [here](https://github.com/ExplorViz/explorviz-backend/blob/settings-service/user-service/src/main/java/net/explorviz/security/server/main/Application.java).

Am I missing something? I might be too tired...

**Comment by lotzk** [comment]
My bad, I did not test against the updated  explorviz-backend-shared version. Please reject this merge request. The current HEAD of this branch (4f200c87db11d9c7e41efe661aca00ba394f0412) should fix this. 

Be aware that I could not test this so far since I don't have docker setup on my home machine.

**Comment by Alexander-Krause** [comment]
No need to reject, right? Branch was updated.

**Comment by Alexander-Krause** [comment]
The latest commits look very promising. I would like to highlight some minor refactoring:

- Outsource model package to subproject of settings-service
- Rename `CustomSetting` as suggested
- Use private no-arg constructors for Morphia, not public
- Refactor JSON-API type names to lower case , not camel case.
- Implement initial save of default settings in SetupApplicationListener.
- Do we need two (mostly) identical MessageBodyReader? 
- Can we use the generic JsonApiProvider from the shared/common-concerns project or does the MessageBodyWriter prevent the usage? We might split the JsonApiProvider in two classes if required.
- JavaDoc for classes

**Pull request merged**
